### ISSUE TITLE
Icone

### ISSUE THREAD

**Issue by jambtc** [napoliblockchain/volontaricovid#2]
qualche volenteroso che mi trasforma le icone 

[icons.zip](https://github.com/jambtc/dali/files/4409265/icons.zip)

**Comment by jambtc** [comment]
MAgari ARMANDO, ma non riesco a contattarlo

**Comment by jambtc** [comment]
scaricate il file icons.zip.

e fate anche un logo, please

**Comment by chiacchio79** [comment]
Senza logo Napoli Blockchain
![2020-04-01_011003](https://user-images.githubusercontent.com/60775378/78085041-157f5880-73ba-11ea-953d-bbfe0bf1eb37.jpg)

Con logo Napoli Blockchain
![2020-04-01_013650](https://user-images.githubusercontent.com/60775378/78085043-16b08580-73ba-11ea-873c-672d4c5490bc.jpg)

**Comment by jambtc** [comment]
caricato ultimo come logo. Mi servono i diversi formati per la pwa, ci sono?

**Comment by bparretta** [comment]
Ultimo a destra

**Comment by chiacchio79** [comment]
![logo-volontari-covid](https://user-images.githubusercontent.com/60775378/78153330-3b990d00-743b-11ea-9ce5-584cf0cfef50.png)

**Comment by jambtc** [comment]
fatto!
